palabras_faciles = [
    'vaca', 'edificio', 'correr', 'casa', 'arbol', 'planeta',
    'montaña', 'rio', 'oceano', 'sol', 'luna', 'estrella',
    'computadora', 'telefono', 'television', 'automovil', 'bicicleta',
    'helado', 'pizza', 'hamburguesa', 'ensalada', 'fruta',
    'libro', 'pintura', 'musica', 'pelicula', 'teatro',
    'familia', 'amigo', 'amor', 'odio', 'alegria',
    'tristeza', 'miedo', 'sorpresa', 'enfado', 'paz',
    'guerra', 'historia', 'ciencia', 'arte', 'matematicas',
    'universidad', 'trabajo', 'viaje', 'aventura', 'sueño',
    'fantasia', 'realidad', 'tiempo', 'espacio', 'vida',
    'muerte', 'naturaleza', 'ciudad', 'pais', 'mundo',
    'tecnologia', 'innovacion', 'creatividad', 'aprendizaje', 'desarrollo',
    'cultura', 'religion', 'filosofia', 'politica', 'economia',
    'medicina', 'deporte', 'juego', 'jugador', 'equipo',
    'celebridad', 'fama', 'historia', 'futuro', 'pasado',
    'presente', 'solucion', 'problema', 'exito', 'fracaso',
    'esperanza', 'deseo', 'objetivo', 'satisfaccion', 'desafio',
    'crecimiento', 'cambio', 'transformacion', 'magia', 'avance',
    'diferencia', 'similitud', 'complejidad', 'simplicidad', 'recompensa',
    'riesgo', 'ganancia', 'perdida', 'belleza', 'fealdad',
    'pintor', 'artista', 'cientifico', 'escritor', 'musico', 'actor',
    'director', 'empresa', 'cliente', 'empleado', 'jefe', 'colega',
    'profesor', 'estudiante', 'escuela', 'universidad', 'aula', 'examen',
    'investigacion', 'descubrimiento', 'invento', 'tecnologia', 'internet',
    'redes', 'social', 'comunicacion', 'viaje', 'aventura', 'exploracion',
    'naturaleza', 'animal', 'planta', 'ecosistema', 'clima', 'planeta',
    'sistema', 'estructura', 'organizacion', 'comunidad', 'sociedad',
    'cultura', 'tradicion', 'historia', 'origen', 'identidad', 'religion',
    'creencia', 'espiritualidad', 'filosofia', 'pensamiento', 'ideologia',
    'politica', 'gobierno', 'poder', 'derechos', 'responsabilidad',
    'economia', 'mercado', 'dinero', 'riqueza', 'pobreza', 'trabajo',
    'industria', 'innovacion', 'teoria', 'practica', 'aprendizaje',
    'educacion', 'salud', 'medicina', 'enfermedad', 'tratamiento',
    'deporte', 'juego', 'estrategia', 'jugador', 'equipo', 'competencia',
    'celebridad', 'fama', 'historia', 'futuro', 'pasado', 'presente',
    'solucion', 'problema', 'exito', 'fracaso', 'esperanza', 'deseo',
    'objetivo', 'satisfaccion', 'desafio', 'crecimiento', 'cambio',
    'transformacion', 'magia', 'avance', 'diferencia', 'similitud',
    'complejidad', 'simplicidad', 'recompensa', 'riesgo', 'ganancia',
    'perdida', 'belleza', 'fealdad', 'arte', 'creatividad', 'imaginacion',
    'emocion', 'sentimiento', 'amor', 'odio', 'alegria', 'tristeza',
    'miedo', 'sorpresa', 'enfado', 'paz', 'guerra']

palabras_expertas = [
    'vaca', 'edificio', 'correr', 'casa', 'arbol', 'planeta',
    'montaña', 'rio', 'oceano', 'sol', 'luna', 'estrella',
    'computadora', 'telefono', 'television', 'automovil', 'bicicleta',
    'helado', 'pizza', 'hamburguesa', 'ensalada', 'fruta',
    'libro', 'pintura', 'musica', 'pelicula', 'teatro',
    'familia', 'amigo', 'amor', 'odio', 'alegria',
    'tristeza', 'miedo', 'sorpresa', 'enfado', 'paz',
    'guerra', 'historia', 'ciencia', 'arte', 'matematicas',
    'universidad', 'trabajo', 'viaje', 'aventura', 'sueño',
    'fantasia', 'realidad', 'tiempo', 'espacio', 'vida',
    'muerte', 'naturaleza', 'ciudad', 'pais', 'mundo',
    'tecnologia', 'innovacion', 'creatividad', 'aprendizaje', 'desarrollo',
    'cultura', 'religion', 'filosofia', 'politica', 'economia',
    'medicina', 'deporte', 'juego', 'jugador', 'equipo',
    'celebridad', 'fama', 'historia', 'futuro', 'pasado',
    'presente', 'solucion', 'problema', 'exito', 'fracaso',
    'esperanza', 'deseo', 'objetivo', 'satisfaccion', 'desafio',
    'crecimiento', 'cambio', 'transformacion', 'magia', 'avance',
    'diferencia', 'similitud', 'complejidad', 'simplicidad', 'recompensa',
    'riesgo', 'ganancia', 'perdida', 'belleza', 'fealdad',
    'pintor', 'artista', 'cientifico', 'escritor', 'musico', 'actor',
    'director', 'empresa', 'cliente', 'empleado', 'jefe', 'colega',
    'profesor', 'estudiante', 'escuela', 'universidad', 'aula', 'examen',
    'investigacion', 'descubrimiento', 'invento', 'tecnologia', 'internet',
    'redes', 'social', 'comunicacion', 'viaje', 'aventura', 'exploracion',
    'naturaleza', 'animal', 'planta', 'ecosistema', 'clima', 'planeta',
    'sistema', 'estructura', 'organizacion', 'comunidad', 'sociedad',
    'cultura', 'tradicion', 'historia', 'origen', 'identidad', 'religion',
    'creencia', 'espiritualidad', 'filosofia', 'pensamiento', 'ideologia',
    'politica', 'gobierno', 'poder', 'derechos', 'responsabilidad',
    'economia', 'mercado', 'dinero', 'riqueza', 'pobreza', 'trabajo',
    'industria', 'innovacion', 'teoria', 'practica', 'aprendizaje',
    'educacion', 'salud', 'medicina', 'enfermedad', 'tratamiento',
    'deporte', 'juego', 'estrategia', 'jugador', 'equipo', 'competencia',
    'celebridad', 'fama', 'historia', 'futuro', 'pasado', 'presente',
    'solucion', 'problema', 'exito', 'fracaso', 'esperanza', 'deseo',
    'objetivo', 'satisfaccion', 'desafio', 'crecimiento', 'cambio',
    'transformacion', 'magia', 'avance', 'diferencia', 'similitud',
    'complejidad', 'simplicidad', 'recompensa', 'riesgo', 'ganancia',
    'perdida', 'belleza', 'fealdad', 'arte', 'creatividad', 'imaginacion',
    'emocion', 'sentimiento', 'amor', 'odio', 'alegria', 'tristeza',
    'miedo', 'sorpresa', 'enfado', 'paz', 'guerra', 'paradigma', 
    'efervescencia', 'anacronismo', 'efimero', 'conjetura', 'sinergia', 
    'esoterico', 'paradoja', 'efluvio', 'proclividad', 'perplejidad',
    'ambigüedad', 'uberrimo', 'innuendo', 'pletora', 'quimera', 'ludico',
    'retorica', 'cognoscible', 'epistemologia', 'sine qua non', 'intrinseco',
    'magnanimo', 'sui generis', 'visceral', 'perdurable', 'iridiscente',
    'aureo', 'apocrifo', 'exegesis', 'efervescente', 'crepusculo', 'effusus',
    'exquisito', 'idiosincrasia', 'insipido', 'sesquipedalio', 'efluvios',
    'nebuloso', 'anacronico', 'inefable', 'uberrima', 'prosopopeya',
    'reverberacion', 'obnubilar', 'serendipia', 'eflorescente', 'empireo',
    'inextricable', 'peregrinacion', 'vivaz', 'volatil', 'cataclismo',
    'cromatico', 'decadencia', 'sibilino', 'parabola', 'laud', 'sibilancia',
    'delectacion', 'placido', 'analogia', 'oscilacion', 'contumacia',
    'prerrogativa', 'amalgama', 'afable', 'eficacia', 'reliquia', 'enigma',
    'infimo', 'homunculo', 'faustico', 'sacrilego', 'iconico', 'bizarro',
    'incubo', 'ultrajante', 'profundo', 'candente', 'copioso', 'quid pro quo',
    'concatenacion', 'efluente', 'abstruso', 'linaje', 'perentorio', 'anatema',
    'exegeta', 'eclecticismo', 'arbitrario', 'neofito', 'onirico', 'serafico',
    'quijotesco', 'compendio', 'convalecencia', 'debilitamiento', 'efronteria',
    'propincuidad', 'consternacion', 'desasosiego', 'melancolia', 'efervescencia',
    'paroxismo', 'zafarrancho', 'perplejidad', 'insoslayable', 'iridiscente',
    'intransigente', 'paradigma', 'efimero', 'inmaculado', 'acucioso', 'peregrinaje',
    'uberrimo', 'quimerico', 'incolume', 'reminiscencia', 'sibarita', 'exacerbado',
    'elocuencia', 'sagacidad', 'procrastinacion', 'providencia', 'eclecticismo',
    'merma', 'idiosincrasia', 'esplendido', 'exhortacion', 'disentir', 'aspaviento',
    'placido', 'sosegado', 'eflorescencia', 'ambivalencia', 'serendipia',
    'resiliencia', 'vicisitud', 'desden', 'efusivo', 'egregio', 'quid pro quo',
    'intrincado', 'sesquipedalio', 'contumacia', 'quintaesencia', 'iniquidad',
    'inefable', 'concentrico', 'enervante', 'perentorio', 'quijotesco', 'acerrimo',
    'voragine', 'ambito', 'parabola', 'exegesis', 'delectacion', 'enigma',
    'nebuloso', 'anacronico', 'plenitud', 'sutil', 'acumen', 'nihilismo',
    'complacencia', 'inopia', 'superfluo', 'peregrinacion', 'profundo',
    'contemplativo', 'enervante', 'sublime', 'efluvio', 'vicario', 'sintetico',
    'imponderable', 'desvario', 'inmaculado', 'imbuir', 'magnanimo', 'plenipotenciario',
    'abjuracion', 'effusus', 'adefesio', 'paradoja', 'protervo', 'osadia', 'pudico',
    'albricias', 'lampiño', 'acaudalado', 'relumbre', 'opulencia', 'resarcimiento',
    'infausto', 'macabro', 'quijotesco', 'anatema', 'despota', 'insurgente', 'somero'
    ]


# Convierte todas las palabras en MAYuSCULAS
palabras_faciles = [palabra.upper() for palabra in palabras_faciles]
palabras_expertas = [palabra.upper() for palabra in palabras_expertas]